before_install:
- gem install bundler
langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: X/1pgktcJy15sQNiLSY6kXkO4nZh34ntkmO7C4Eq+xDE3pUMpXspPY8APRIV60mHmoExqtpSLBfTFp3sAJuUcH+TGDCHApIgwmejWzHIAxVZmZdkOfWpSfVrn4EpCwI2UKqksLyZDmjmIkSZtaE2SwGm3IgGemZwD923FI6qhW3UyM0pkQ1dtTR29NCYFjVicvRQauocl9d/C852Q8kqa2up1GP1dLRloQ8SxDQ9Xc1zu+1zzdscrhK2sMheyCGaj2xbBVin+te9yOA7RgCsjO5GRmPExzUuNHNVANs4agD9ytLW0wd8LD7/kX6ammbXK65qJrov/RzWSpcCCAQdXT69wB/V5PzkW+RMHMUi17iWImi0qspMyYy7p5gXJZPg7UubP4BW2fGgPmMaLuwW0+9HxN0ZqdrYbtSYF3zi/xQh68zmwyNcF5Jjyh3sXQr+KuWoPuLswU/YA3HYk3mBp6GOkxtg8BzIIqZaimC0CAd6vPHJievIfTtXJSXsrxELRHWOJxHY2s1W2/X+qjBUGdBP0zbzA+5Dsy6O668h/Rs7EnzLdM3m6/tsTSl7/xZ9WfK+bdiyhyh/CmNnakM6oKTp9EU0YwE3xlINlEWkDRcBiZsIdHa8OsjJmWDI5HgmUVXGLcu6gsnClmARPS+0eHFqFwthOUa1nsfCOvsJhtU=
  app: obituary-hub
  run: rails db:migrate
